-- ==========================================
-- LogiSync Pro - Full Database Schema
-- ==========================================

-- 1. Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. Create Personnel Table
CREATE TABLE IF NOT EXISTS public.personnel (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    employee_id text UNIQUE NOT NULL,
    name text NOT NULL,
    type text CHECK (type IN ('Team Leader', 'Writer Crew', 'Driver')),
    status text DEFAULT 'Available' CHECK (status IN ('Available', 'Annual Leave', 'Sick Leave', 'Personal Leave')),
    emirates_id text UNIQUE NOT NULL,
    license_number text,
    created_at timestamp with time zone DEFAULT now()
);

-- 3. Create Vehicles Table
CREATE TABLE IF NOT EXISTS public.vehicles (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    name text NOT NULL,
    plate text UNIQUE NOT NULL,
    status text DEFAULT 'Available' CHECK (status IN ('Available', 'Out of Service', 'Maintenance')),
    created_at timestamp with time zone DEFAULT now()
);

-- 4. Create System Users Table
CREATE TABLE IF NOT EXISTS public.system_users (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    employee_id text UNIQUE NOT NULL,
    name text NOT NULL,
    role text DEFAULT 'USER' CHECK (role IN ('ADMIN', 'USER')),
    permissions jsonb NOT NULL DEFAULT '{}'::jsonb,
    avatar text,
    status text DEFAULT 'Active' CHECK (status IN ('Active', 'Disabled')),
    created_at timestamp with time zone DEFAULT now()
);

-- 5. Create Jobs Table
CREATE TABLE IF NOT EXISTS public.jobs (
    id text PRIMARY KEY, -- Job No.
    title text NOT NULL,
    shipper_name text NOT NULL,
    shipper_phone text,
    client_email text,
    location text,
    shipment_details text,
    description text,
    priority text DEFAULT 'MEDIUM' CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH')),
    agent_name text,
    loading_type text NOT NULL,
    main_category text,
    sub_category text,
    shuttle text CHECK (shuttle IN ('Yes', 'No')),
    long_carry text CHECK (long_carry IN ('Yes', 'No')),
    special_requests jsonb DEFAULT '{}'::jsonb,
    volume_cbm numeric(10,2),
    job_time text,
    job_date date NOT NULL,
    duration integer DEFAULT 1,
    status text DEFAULT 'ACTIVE' CHECK (status IN ('PENDING_ADD', 'PENDING_DELETE', 'ACTIVE', 'COMPLETED', 'REJECTED')),
    created_at bigint DEFAULT (extract(epoch from now()) * 1000)::bigint,
    requester_id text,
    assigned_to text,
    is_warehouse_activity boolean DEFAULT false,
    is_import_clearance boolean DEFAULT false,
    is_transporter boolean DEFAULT false,
    is_locked boolean DEFAULT false,
    last_edited_by text,
    last_edited_at bigint,
    
    -- Admin allocations
    team_leader text,
    writer_crew text[],
    vehicle text, -- Legacy
    vehicles text[],
    
    -- Import Clearance
    bol_number text,
    container_number text,
    customs_status text,
    customs_history jsonb DEFAULT '[]'::jsonb,
    
    -- Tracking
    tracking_current_step integer DEFAULT 0,
    tracking_data jsonb DEFAULT '{}'::jsonb,
    
    -- Warehouse
    activity_name text,
    
    -- Transporter
    drop_off_locations text[],
    transporter_status text DEFAULT 'Scheduled'
);

-- 6. Create System Settings Table
CREATE TABLE IF NOT EXISTS public.system_settings (
    id integer PRIMARY KEY DEFAULT 1,
    daily_job_limits jsonb DEFAULT '{}'::jsonb,
    holidays text[] DEFAULT '{}'::text[],
    company_logo text,
    system_alert jsonb DEFAULT '{"active": false, "title": "", "message": "", "type": "info"}'::jsonb,
    updated_at timestamp with time zone DEFAULT now()
);

-- 7. Create Inventory Items Table
CREATE TABLE IF NOT EXISTS public.inventory_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code text UNIQUE NOT NULL,
    description text,
    unit text,
    price numeric(10,2) DEFAULT 0,
    stock integer DEFAULT 0,
    opening_stock integer DEFAULT 0,
    purchased_stock integer DEFAULT 0,
    critical_stock integer DEFAULT 0,
    is_outsource boolean DEFAULT false,
    vendor_name text,
    outsource_type text,
    truck_schedule text,
    location text,
    created_at timestamp with time zone DEFAULT now()
);

-- 8. Create Inventory Purchases Table
CREATE TABLE IF NOT EXISTS public.inventory_purchases (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_id bigint REFERENCES public.inventory_items(id) ON DELETE CASCADE,
    quantity integer NOT NULL,
    purchase_date date NOT NULL DEFAULT CURRENT_DATE,
    created_at timestamp with time zone DEFAULT now()
);

-- 9. Create Inventory Consumption Table
CREATE TABLE IF NOT EXISTS public.inventory_consumption (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    inventory_id bigint REFERENCES public.inventory_items(id) ON DELETE CASCADE,
    job_id text NOT NULL,
    quantity integer NOT NULL,
    consumption_date date NOT NULL DEFAULT CURRENT_DATE,
    created_at timestamp with time zone DEFAULT now()
);

-- 10. Create Inventory Price History Table
CREATE TABLE IF NOT EXISTS public.inventory_price_history (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    inventory_id bigint REFERENCES public.inventory_items(id) ON DELETE CASCADE,
    price numeric(10,2) NOT NULL,
    effective_date date NOT NULL DEFAULT CURRENT_DATE,
    created_at timestamp with time zone DEFAULT now()
);

-- 11. Create Job Cost Sheets Table
CREATE TABLE IF NOT EXISTS public.job_cost_sheets (
    job_id text PRIMARY KEY,
    items jsonb NOT NULL DEFAULT '[]'::jsonb,
    status text NOT NULL DEFAULT 'Issued' CHECK (status IN ('Issued', 'Returned', 'Finalized')),
    total_cost numeric(12,2) DEFAULT 0,
    packing_date date,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

-- 12. Enable Row Level Security (RLS)
ALTER TABLE public.personnel ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vehicles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_purchases ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_consumption ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_price_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.job_cost_sheets ENABLE ROW LEVEL SECURITY;

-- 13. Create RLS Policies (Allow all for all users)
-- Note: In a production environment, these should be more restrictive based on user roles.
DO $$ 
BEGIN
    -- Drop existing restrictive policies if they exist
    DROP POLICY IF EXISTS "Allow all for authenticated" ON public.personnel;
    DROP POLICY IF EXISTS "Allow all for authenticated" ON public.vehicles;
    DROP POLICY IF EXISTS "Allow all for authenticated" ON public.system_users;
    DROP POLICY IF EXISTS "Allow all for authenticated" ON public.jobs;
    DROP POLICY IF EXISTS "Allow all for authenticated" ON public.system_settings;
    DROP POLICY IF EXISTS "Allow all for authenticated" ON public.inventory_items;
    DROP POLICY IF EXISTS "Allow all for authenticated" ON public.inventory_purchases;
    DROP POLICY IF EXISTS "Allow all for authenticated" ON public.inventory_consumption;
    DROP POLICY IF EXISTS "Allow all for authenticated" ON public.inventory_price_history;
    DROP POLICY IF EXISTS "Allow all for authenticated" ON public.job_cost_sheets;

    -- Create new inclusive policies
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow all' AND tablename = 'personnel') THEN
        CREATE POLICY "Allow all" ON public.personnel FOR ALL USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow all' AND tablename = 'vehicles') THEN
        CREATE POLICY "Allow all" ON public.vehicles FOR ALL USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow all' AND tablename = 'system_users') THEN
        CREATE POLICY "Allow all" ON public.system_users FOR ALL USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow all' AND tablename = 'jobs') THEN
        CREATE POLICY "Allow all" ON public.jobs FOR ALL USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow all' AND tablename = 'system_settings') THEN
        CREATE POLICY "Allow all" ON public.system_settings FOR ALL USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow all' AND tablename = 'inventory_items') THEN
        CREATE POLICY "Allow all" ON public.inventory_items FOR ALL USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow all' AND tablename = 'inventory_purchases') THEN
        CREATE POLICY "Allow all" ON public.inventory_purchases FOR ALL USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow all' AND tablename = 'inventory_consumption') THEN
        CREATE POLICY "Allow all" ON public.inventory_consumption FOR ALL USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow all' AND tablename = 'inventory_price_history') THEN
        CREATE POLICY "Allow all" ON public.inventory_price_history FOR ALL USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow all' AND tablename = 'job_cost_sheets') THEN
        CREATE POLICY "Allow all" ON public.job_cost_sheets FOR ALL USING (true);
    END IF;
END $$;

-- 14. Insert Initial Settings
INSERT INTO public.system_settings (id, daily_job_limits, holidays)
VALUES (1, '{}'::jsonb, '{}'::text[])
ON CONFLICT (id) DO NOTHING;

-- 15. Refresh PostgREST schema cache
NOTIFY pgrst, 'reload schema';
